INSERT INTO Violation (ViolationID, InspectionID, ViolationCode, ViolationDescription, CriticalFlag) VALUES (1, 1, '08A', 'Establishment is not free of harborage or conditions conducive to rodents, insects or other pests.', 'Not Critical');
INSERT INTO Violation (ViolationID, InspectionID, ViolationCode, ViolationDescription, CriticalFlag) VALUES (2, 2, '06D', 'Food contact surface not properly washed, rinsed and sanitized after each use and following any activity when contamination may have occurred.', 'Critical');
INSERT INTO Violation (ViolationID, InspectionID, ViolationCode, ViolationDescription, CriticalFlag) VALUES (3, 3, '02B', 'Hot TCS food item not held at or above 140 °F.', 'Critical');
INSERT INTO Violation (ViolationID, InspectionID, ViolationCode, ViolationDescription, CriticalFlag) VALUES (4, 4, '04L', 'Evidence of mice or live mice present in facility''s food and/or non-food areas.', 'Critical');
INSERT INTO Violation (ViolationID, InspectionID, ViolationCode, ViolationDescription, CriticalFlag) VALUES (5, 5, '08A', 'Establishment is not free of harborage or conditions conducive to rodents, insects or other pests.', 'Not Critical');
INSERT INTO Violation (ViolationID, InspectionID, ViolationCode, ViolationDescription, CriticalFlag) VALUES (6, 6, '04K', 'Evidence of rats or live rats in establishment''s food or non-food areas.', 'Critical');
INSERT INTO Violation (ViolationID, InspectionID, ViolationCode, ViolationDescription, CriticalFlag) VALUES (7, 7, '04N', 'Filth flies or food/refuse/sewage associated with (FRSA) flies or other nuisance pests in establishment’s food and/or non-food areas. FRSA flies include house flies, blow flies, bottle flies, flesh flies, drain flies, Phorid flies and fruit flies.', 'Critical');
INSERT INTO Violation (ViolationID, InspectionID, ViolationCode, ViolationDescription, CriticalFlag) VALUES (8, 8, '04L', 'Evidence of mice or live mice in establishment''s food or non-food areas.', 'Critical');
INSERT INTO Violation (ViolationID, InspectionID, ViolationCode, ViolationDescription, CriticalFlag) VALUES (9, 9, '10F', 'Non-food contact surface improperly constructed. Unacceptable material used. Non-food contact surface or equipment improperly maintained and/or not properly sealed, raised, spaced or movable to allow accessibility for cleaning on all sides, above and underneath the unit.', 'Not Critical');
